version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/my-mac
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ljq
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

